### ISSUE TITLE
Training pose estimation openpifpaf with  a new dataset 

### ISSUE THREAD

**Issue by TinhTranXuan** [DuncanZauss/openpifpaf_mpii#2]
Hello @DuncanZauss
Thank you for contributing to creating a plugin support training pose estimation openpifpaf with the MPII dataset.
I have my dataset created based on the MPII dataset and I have a few difficulties. I hope you explain and clear my question.
I have used key points: head bottom, head top, left shoulder, right shoulder, left elbow, right elbow, left wrist, and right wrist for my dataset, detailed in my picture below:
![image](https://github.com/DuncanZauss/openpifpaf_mpii/assets/44960020/3d67fe25-6de9-4dd8-b21c-80a2a1d2c7a3)

Can you guide me to modify based on the MPII dataset to training pose estimation openpifpaf??
I looking forward to a response from you.

Thank you very much.

**Comment by DuncanZauss** [comment]
Hi @TinhTranXuan ,
Thank you for using OpenPifPaf!
We have an extensive tutorial on how to add a dataset here: https://openpifpaf.github.io/plugins_custom.html
If you want to add your dataset based on MPII, you would need to modify the dataset constants here:
https://github.com/DuncanZauss/openpifpaf_mpii/blob/main/openpifpaf_mpii/constants.py
Here is a quick explanation of the constants:
- KEYPOINTS: Names of the keypoints
- SIGMAS: Size of the keypoint used for the loss computation
- UPRIGHT_POSE: 2D points to visualize the pose (i.e. like in the screenshot you sent, mainly to check if the dataset looks as expected)
- SKELETON: With the indices from KEYPOINTS define a list which specifies the keypoint connections, i.e. for the screenshot you sent it would be `[[0,1], [4,3], [3,2] and so on...]`
- HFLIP: Dict that maps the corresponding left keypoint to the corresponding right keypoint. This used for dataset augmentation during training (i.e. flipping images alongside the corresponding ground truth)
- CATEGORIES: This is in case of multiple object types in the scene, i.e. for this case it can just be ["person"]
- SCORE_WEIGHTS: Per keypoint weight for the loss. For the start you could just weigh all keypoints equally, i.e. set all weights to the same value.
- DENSER_CONNECTIONS: Optional, same as skeleton, just with more connections. For your case, you could maybe add connections form 0 to 5 and 0 to 2 here
You then just need to change the naming here https://github.com/DuncanZauss/openpifpaf_mpii/blob/main/openpifpaf_mpii/mpii.py
Additionally, you would need to write a funtion that transforms your dataset annotations to COCO style like I did here: https://github.com/DuncanZauss/openpifpaf_mpii/blob/main/openpifpaf_mpii/MPII_to_COCO.py

I hope this helps!
